apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: yoga-booker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: app
          image: docker.io/eandmsz/booking-service:2.0.0
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: postgresql://yoga:yoga@postgres.yoga-booker.svc.cluster.local:5432/yoga
            - name: CLASS_SERVICE_BASE_URL
              value: http://class-service.yoga-booker.svc.cluster.local:8000
            - name: RABBITMQ_URL
              value: amqp://rabbit:rabbit@rabbitmq.yoga-booker.svc.cluster.local:5672/%2f
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: yoga-booker
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booking-service-hpa
  namespace: yoga-booker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
